name: Publish to Packages
description: Publish packages to Buildkite Packages
author: https://github.com/buildkite-plugins
requirements:
  - python3
  - curl
configuration:
  properties:
    artifacts:
      type: string
    registry:
      type: string
    attestations:
      type: string
    artifact_build_id:
      type: string
  required:
    - artifacts
    - registry
  additionalProperties: false
