name: Publish to Packages
description: Publish packages to Buildkite Packages
author: https://github.com/buildkite-plugins
requirements:
  - bash
configuration:
  properties:
    files:
      type: string
    registry:
      type: string
  required:
    - files
    - registry
  additionalProperties: false
