steps:
  - label: ":python: Type check"
    command: "docker run --rm -v $(pwd):/data cytopia/mypy:latest-py3.10 --strict **/*.py"

  - label: ":python: Unit tests"
    command: "python3 -m unittest tests/*.py"
    plugins:
      - docker#v5.11.0:
          image: "python:3.10-alpine"

  - label: ":sparkles: Lint"
    plugins:
      - plugin-linter#v3.3.0:
          id: publish-to-packages

  - label: ":shell: Shellcheck"
    plugins:
      - shellcheck#v1.3.0:
          files:
            - hooks/**
            - lib/**
