#!/usr/bin/env bash

# `set -x` if DEBUG_SCRIPT is set to anything at all
if [[ -n "${DEBUG_SCRIPT}" ]]; then
  set -x
fi

set -euo pipefail

DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

# shellcheck source=lib/plugin.bash
. "$DIR/../lib/plugin.bash"

ARTIFACTS="$(plugin_read_config ARTIFACTS "")"
REGISTRY="$(plugin_read_config REGISTRY "")"

if [[ "${REGISTRY}" =~ "/" ]]; then
  ORGANIZATION_SLUG="${REGISTRY%/*}"
else
  ORGANIZATION_SLUG="${BUILDKITE_ORGANIZATION_SLUG}"
fi

REGISTRY_SLUG="${REGISTRY#*/}"

echo "--- Download artifacts"
buildkite-agent artifact download "${ARTIFACTS}" .

echo "--- Request OIDC token"
TOKEN="$(buildkite-agent oidc request-token --audience "https://packages.buildkite.com/${ORGANIZATION_SLUG}/${REGISTRY_SLUG}" --lifetime 300)"

echo "--- Publish to Buildkite Packages"
declare -a UNGLOBBED_FILES="($ARTIFACTS)" # expand glob
for FILE in "${UNGLOBBED_FILES[@]}"; do
  curl --fail-with-body -X POST "https://api.buildkite.com/v2/packages/organizations/${ORGANIZATION_SLUG}/registries/${REGISTRY_SLUG}/packages" \
    -H "Authorization: Bearer $TOKEN" \
    -F "file=@$FILE"
done
