#!/usr/bin/env bash
set -euo pipefail

DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

# shellcheck source=lib/plugin.bash
. "$DIR/../lib/plugin.bash"

FILES="$(plugin_read_config FILES "")"
REGISTRY="$(plugin_read_config REGISTRY "")"

if [[ "${REGISTRY}" =~ "/" ]]; then
  ORGANIZATION_SLUG="${REGISTRY%/*}"
else
  ORGANIZATION_SLUG="${BUILDKITE_ORGANIZATION_SLUG}"
fi

REGISTRY_SLUG="${REGISTRY#*/}"

echo "--- Downloading artifacts"
buildkite-agent artifact download "${FILES}" .

echo "--- Requesting OIDC token"
TOKEN="$(buildkite-agent oidc request-token --audience "https://packages.buildkite.com/${ORGANIZATION_SLUG}/${REGISTRY_SLUG}" --lifetime 300)"

echo "--- Pushing to Buildkite Packages"
declare -a UNGLOBBED_FILES="($FILES)" # expand glob
for FILE in "${UNGLOBBED_FILES[@]}"; do
  curl --fail -X POST "https://api.buildkite.com/v2/packages/organizations/${ORGANIZATION_SLUG}/registries/${REGISTRY_SLUG}/packages" \
    -H "Authorization: Bearer $TOKEN" \
    -F "file=@$FILE"
done
